name: run-compartmental-model-server
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: nightly
        arch: arm
    - run: julia --project bin/main.jl
